// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_unused_result_type`, `err_msg`, `service`, `to_summary`

/// 打开（或创建）书库，指定数据目录。应用启动时调用一次。
Future<void> libraryOpen({required String dataDir}) =>
    RustLib.instance.api.crateApiLibraryOpen(dataDir: dataDir);

/// 导入一个书籍文件（解析 → 规范 EPUB 缓存 → 入库），返回书库条目。
Future<BookSummary> libraryImport({required String path}) =>
    RustLib.instance.api.crateApiLibraryImport(path: path);

/// 书架列表（按添加时间倒序）
Future<List<BookSummary>> libraryList() =>
    RustLib.instance.api.crateApiLibraryList();

/// 删除书籍
Future<void> libraryRemove({required String id}) =>
    RustLib.instance.api.crateApiLibraryRemove(id: id);

/// 打开书：返回元数据与全部章节文本（P0 滚动模式直接渲染）
Future<BookView> bookOpen({required String id}) =>
    RustLib.instance.api.crateApiBookOpen(id: id);

/// 取规范 EPUB 中某章节的原始 HTML（WebView 分页渲染用，REQ-001）
Future<String> bookChapterHtml({required String id, required String href}) =>
    RustLib.instance.api.crateApiBookChapterHtml(id: id, href: href);

/// 取规范 EPUB 中某资源（图片/CSS/字体）的字节
Future<Uint8List> bookResource({required String id, required String path}) =>
    RustLib.instance.api.crateApiBookResource(id: id, path: path);

/// 保存阅读进度（href + 章内进度 0..1）
Future<void> progressSave(
        {required String id,
        required String href,
        required double progression}) =>
    RustLib.instance.api
        .crateApiProgressSave(id: id, href: href, progression: progression);

/// 读取阅读进度（无记录返回 None）
Future<ProgressView?> progressGet({required String id}) =>
    RustLib.instance.api.crateApiProgressGet(id: id);

/// 书架条目
class BookSummary {
  final String id;
  final String title;
  final List<String> authors;
  final String? language;
  final String format;

  const BookSummary({
    required this.id,
    required this.title,
    required this.authors,
    this.language,
    required this.format,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authors.hashCode ^
      language.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authors == other.authors &&
          language == other.language &&
          format == other.format;
}

/// 打开的书（元数据 + 全部章节纯文本）
class BookView {
  final String id;
  final String title;
  final List<ChapterView> chapters;

  const BookView({
    required this.id,
    required this.title,
    required this.chapters,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          chapters == other.chapters;
}

/// 章节视图（阅读器用）
class ChapterView {
  final String title;
  final String text;

  const ChapterView({
    required this.title,
    required this.text,
  });

  @override
  int get hashCode => title.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterView &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          text == other.text;
}

/// 阅读进度视图（桥接）
class ProgressView {
  final String href;
  final double progression;

  const ProgressView({
    required this.href,
    required this.progression,
  });

  @override
  int get hashCode => href.hashCode ^ progression.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressView &&
          runtimeType == other.runtimeType &&
          href == other.href &&
          progression == other.progression;
}
