// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_unused_result_type`, `book_title_of`, `books_in_scope`, `chapter_text`, `chapter_titles`, `dict_service`, `domain_scope`, `ensure_indexed`, `err_msg`, `indexed_chapters`, `notes_service`, `search_service`, `service`, `to_annotation_view`, `to_group_view`, `to_hit_view`, `to_locator_view`, `to_summary`, `translation_service`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TextSelectionView`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 打开（或创建）书库，指定数据目录。应用启动时调用一次。
/// 装配：SERVICE（既有）+ DICT/TRANSLATION 双单例（REQ-003 02-design §4.1）。
Future<void> libraryOpen({required String dataDir}) =>
    RustLib.instance.api.crateApiLibraryOpen(dataDir: dataDir);

/// 导入一个书籍文件（解析 → 规范 EPUB 缓存 → 入库 + 建搜索索引），返回书库条目。
Future<BookSummary> libraryImport({required String path}) =>
    RustLib.instance.api.crateApiLibraryImport(path: path);

/// 书架列表（按添加时间倒序）
Future<List<BookSummary>> libraryList() =>
    RustLib.instance.api.crateApiLibraryList();

/// 删除书籍
Future<void> libraryRemove({required String id}) =>
    RustLib.instance.api.crateApiLibraryRemove(id: id);

/// 打开书：返回元数据与全部章节文本（P0 滚动模式直接渲染）
Future<BookView> bookOpen({required String id}) =>
    RustLib.instance.api.crateApiBookOpen(id: id);

/// 取规范 EPUB 中某章节的原始 HTML（WebView 分页渲染用，REQ-001）
Future<String> bookChapterHtml({required String id, required String href}) =>
    RustLib.instance.api.crateApiBookChapterHtml(id: id, href: href);

/// 取规范 EPUB 中某资源（图片/CSS/字体）的字节
Future<Uint8List> bookResource({required String id, required String path}) =>
    RustLib.instance.api.crateApiBookResource(id: id, path: path);

/// 保存阅读进度（href + 章内进度 0..1）
Future<void> progressSave(
        {required String id,
        required String href,
        required double progression}) =>
    RustLib.instance.api
        .crateApiProgressSave(id: id, href: href, progression: progression);

/// 读取阅读进度（无记录返回 None）
Future<ProgressView?> progressGet({required String id}) =>
    RustLib.instance.api.crateApiProgressGet(id: id);

/// 安装词库（入参为 .ifo 路径或含 .ifo 的目录）；返回 DictInfoView（US-7）
Future<DictInfoView> dictInstall({required String path}) =>
    RustLib.instance.api.crateApiDictInstall(path: path);

/// 移除词库
Future<void> dictRemove({required String dictId}) =>
    RustLib.instance.api.crateApiDictRemove(dictId: dictId);

/// 已装词库列表（安装顺序）
Future<List<DictInfoView>> dictList() =>
    RustLib.instance.api.crateApiDictList();

/// 查词：Ok(Some(DictEntryView)) 命中 / Ok(None) 未收录（US-2）/ Err（无词库 US-3、损坏 US-6）
Future<DictEntryView?> dictLookup({required String word, String? dictId}) =>
    RustLib.instance.api.crateApiDictLookup(word: word, dictId: dictId);

/// 翻译：缓存优先；命中 from_cache=true（US-10/13）；未配置/网络失败给明确错误（US-12）
Future<TranslationView> translate(
        {required String text, required String from, required String to}) =>
    RustLib.instance.api.crateApiTranslate(text: text, from: from, to: to);

/// 读取当前翻译配置（策略 + 是否已配置 DeepL key + 固定掩码；US-15）
Future<TranslateConfigView> translateGetConfig() =>
    RustLib.instance.api.crateApiTranslateGetConfig();

/// 设置翻译策略（"auto"/"offline"/"deepl"/"echo"）；未知 → Err("未知翻译策略: {s}")（US-15）
Future<void> translateSetStrategy({required String strategy}) =>
    RustLib.instance.api.crateApiTranslateSetStrategy(strategy: strategy);

/// 一键清空翻译缓存（US-13 / docs/04 领域规则4）
Future<void> translateCacheClear() =>
    RustLib.instance.api.crateApiTranslateCacheClear();

/// Provider 最小配置通道：写 settings + 对注册 Provider 调 configure
/// （`translate_set_config("echo", "")` 即无 key 演示，ADR 关联裁定2）
Future<void> translateSetConfig(
        {required String provider, required String key}) =>
    RustLib.instance.api
        .crateApiTranslateSetConfig(provider: provider, key: key);

/// 章文本 → 句列表（US-4/US-7；index 为章内句序号）
Future<List<SentenceChunkView>> ttsSegment(
        {required String bookId, required String href}) =>
    RustLib.instance.api.crateApiTtsSegment(bookId: bookId, href: href);

/// 句索引 → Locator（US-5；越界/章节不存在 → Err）
Future<LocatorView> ttsLocatorForSentence(
        {required String bookId, required String href, required int idx}) =>
    RustLib.instance.api
        .crateApiTtsLocatorForSentence(bookId: bookId, href: href, idx: idx);

/// Locator → 句索引（US-6；api 层重建 domain `Locator` 后调用 domain 函数）
Future<int> ttsSentenceIndexAt(
        {required String bookId,
        required String href,
        required LocatorView locator}) =>
    RustLib.instance.api.crateApiTtsSentenceIndexAt(
        bookId: bookId, href: href, locator: locator);

/// 读取听书设置（缺省 `system_male/1.0/true`；speed clamp `[0.5,3.0]`）
Future<ListenSettingsView> ttsListenSettingsGet() =>
    RustLib.instance.api.crateApiTtsListenSettingsGet();

/// 写入听书设置（speed 落库前 clamp `[0.5,3.0]`）
Future<void> ttsListenSettingsSet({required ListenSettingsView settings}) =>
    RustLib.instance.api.crateApiTtsListenSettingsSet(settings: settings);

/// 创建笔记（高亮/划线/批注）：章全文 → 文本锚 → 落库（US-1/2/3）。
Future<AnnotationView> notesCreate(
        {required String bookId,
        required String href,
        required String text,
        required double progression,
        required String kind,
        String? color,
        String? noteText}) =>
    RustLib.instance.api.crateApiNotesCreate(
        bookId: bookId,
        href: href,
        text: text,
        progression: progression,
        kind: kind,
        color: color,
        noteText: noteText);

/// 更新笔记（批注文本/颜色/kind）。
Future<void> notesUpdate(
        {required String noteId, required NotePatchView patch}) =>
    RustLib.instance.api.crateApiNotesUpdate(noteId: noteId, patch: patch);

Future<void> notesDelete({required String noteId}) =>
    RustLib.instance.api.crateApiNotesDelete(noteId: noteId);

Future<int> notesDeleteMany({required List<String> noteIds}) =>
    RustLib.instance.api.crateApiNotesDeleteMany(noteIds: noteIds);

Future<int> notesDeleteAll({required String bookId}) =>
    RustLib.instance.api.crateApiNotesDeleteAll(bookId: bookId);

/// 列出该书笔记（按章节分组；含书签，US-6/14）。
Future<List<NoteGroupView>> notesList({required String bookId}) =>
    RustLib.instance.api.crateApiNotesList(bookId: bookId);

/// 笔记 id → 位置（面板/书签跳转用）。
Future<LocatorView> notesResolve({required String noteId}) =>
    RustLib.instance.api.crateApiNotesResolve(noteId: noteId);

/// 导出 Markdown / JSON；空笔记 → Err("暂无笔记")（US-16/17）。
Future<ExportSummaryView> notesExport(
        {required String bookId,
        required String fmt,
        required String outPath}) =>
    RustLib.instance.api
        .crateApiNotesExport(bookId: bookId, fmt: fmt, outPath: outPath);

/// 幂等切换书签（US-14）。
Future<BookmarkToggleView> notesToggleBookmark(
        {required String bookId,
        required String href,
        required double progression,
        String? snippet}) =>
    RustLib.instance.api.crateApiNotesToggleBookmark(
        bookId: bookId, href: href, progression: progression, snippet: snippet);

/// 全文搜索（空查询短路；懒回填旧书；CJK bigram；US-18/19/20/21/23）。
Future<List<SearchHitView>> search(
        {required String query, required SearchScopeView scope}) =>
    RustLib.instance.api.crateApiSearch(query: query, scope: scope);

/// 笔记视图（字段与 Dart `AnnotationData` 一一对应）
class AnnotationView {
  final String id;
  final String bookId;
  final String kind;
  final String? color;
  final String href;
  final double progression;
  final String? snippet;
  final String? noteText;
  final int? start;
  final int? end;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String syncStatus;

  const AnnotationView({
    required this.id,
    required this.bookId,
    required this.kind,
    this.color,
    required this.href,
    required this.progression,
    this.snippet,
    this.noteText,
    this.start,
    this.end,
    required this.createdAt,
    required this.updatedAt,
    required this.syncStatus,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      kind.hashCode ^
      color.hashCode ^
      href.hashCode ^
      progression.hashCode ^
      snippet.hashCode ^
      noteText.hashCode ^
      start.hashCode ^
      end.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      syncStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotationView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          kind == other.kind &&
          color == other.color &&
          href == other.href &&
          progression == other.progression &&
          snippet == other.snippet &&
          noteText == other.noteText &&
          start == other.start &&
          end == other.end &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          syncStatus == other.syncStatus;
}

/// 书架条目
class BookSummary {
  final String id;
  final String title;
  final List<String> authors;
  final String? language;
  final String format;

  const BookSummary({
    required this.id,
    required this.title,
    required this.authors,
    this.language,
    required this.format,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authors.hashCode ^
      language.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authors == other.authors &&
          language == other.language &&
          format == other.format;
}

/// 打开的书（元数据 + 全部章节纯文本）
class BookView {
  final String id;
  final String title;
  final List<ChapterView> chapters;

  const BookView({
    required this.id,
    required this.title,
    required this.chapters,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          chapters == other.chapters;
}

/// 书签切换结果视图
class BookmarkToggleView {
  final bool bookmarked;
  final String? noteId;

  const BookmarkToggleView({
    required this.bookmarked,
    this.noteId,
  });

  @override
  int get hashCode => bookmarked.hashCode ^ noteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookmarkToggleView &&
          runtimeType == other.runtimeType &&
          bookmarked == other.bookmarked &&
          noteId == other.noteId;
}

/// 章节视图（阅读器用）
class ChapterView {
  final String title;
  final String text;

  /// 章/资源路径（REQ-009：搜索定位/笔记锚点用；规范 EPUB 内相对路径）
  final String href;

  const ChapterView({
    required this.title,
    required this.text,
    required this.href,
  });

  @override
  int get hashCode => title.hashCode ^ text.hashCode ^ href.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterView &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          text == other.text &&
          href == other.href;
}

/// 词条视图（US-1/16）
class DictEntryView {
  final String word;
  final String? phonetic;
  final String? pos;
  final String definition;
  final String? example;

  const DictEntryView({
    required this.word,
    this.phonetic,
    this.pos,
    required this.definition,
    this.example,
  });

  @override
  int get hashCode =>
      word.hashCode ^
      phonetic.hashCode ^
      pos.hashCode ^
      definition.hashCode ^
      example.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictEntryView &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          phonetic == other.phonetic &&
          pos == other.pos &&
          definition == other.definition &&
          example == other.example;
}

/// 已安装词库信息（US-7；docs/03 §4 原 Result<()>，ADR 关联裁定4 修正）
class DictInfoView {
  final String id;
  final String name;
  final BigInt wordCount;
  final String path;

  const DictInfoView({
    required this.id,
    required this.name,
    required this.wordCount,
    required this.path,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ wordCount.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictInfoView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          wordCount == other.wordCount &&
          path == other.path;
}

/// 导出结果视图
class ExportSummaryView {
  final String path;
  final int noteCount;
  final String format;

  const ExportSummaryView({
    required this.path,
    required this.noteCount,
    required this.format,
  });

  @override
  int get hashCode => path.hashCode ^ noteCount.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSummaryView &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          noteCount == other.noteCount &&
          format == other.format;
}

/// 听书设置视图（settings 表三键的类型化投影）
class ListenSettingsView {
  final String voiceId;

  /// 0.5..=3.0
  final double speed;
  final bool autoNext;

  const ListenSettingsView({
    required this.voiceId,
    required this.speed,
    required this.autoNext,
  });

  @override
  int get hashCode => voiceId.hashCode ^ speed.hashCode ^ autoNext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListenSettingsView &&
          runtimeType == other.runtimeType &&
          voiceId == other.voiceId &&
          speed == other.speed &&
          autoNext == other.autoNext;
}

/// 句级位置视图（不暴露领域 `Locator` 的 `Rect/cfi/page`）
class LocatorView {
  final String bookId;
  final String href;

  /// 章内进度 0..=1
  final double progression;

  /// 全书进度 0..=1（本期=章内近似，仅展示）
  final double totalProgression;

  /// 文本锚片段（`TextAnchor.snippet`；无文本锚为 None）
  final String? snippet;

  const LocatorView({
    required this.bookId,
    required this.href,
    required this.progression,
    required this.totalProgression,
    this.snippet,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      href.hashCode ^
      progression.hashCode ^
      totalProgression.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocatorView &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          href == other.href &&
          progression == other.progression &&
          totalProgression == other.totalProgression &&
          snippet == other.snippet;
}

/// 按章节分组的笔记视图
class NoteGroupView {
  final String chapterTitle;
  final String href;
  final List<AnnotationView> notes;

  const NoteGroupView({
    required this.chapterTitle,
    required this.href,
    required this.notes,
  });

  @override
  int get hashCode => chapterTitle.hashCode ^ href.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteGroupView &&
          runtimeType == other.runtimeType &&
          chapterTitle == other.chapterTitle &&
          href == other.href &&
          notes == other.notes;
}

/// 笔记局部更新视图
class NotePatchView {
  final String? noteText;
  final String? color;
  final String? kind;

  const NotePatchView({
    this.noteText,
    this.color,
    this.kind,
  });

  @override
  int get hashCode => noteText.hashCode ^ color.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotePatchView &&
          runtimeType == other.runtimeType &&
          noteText == other.noteText &&
          color == other.color &&
          kind == other.kind;
}

/// 阅读进度视图（桥接）
class ProgressView {
  final String href;
  final double progression;

  const ProgressView({
    required this.href,
    required this.progression,
  });

  @override
  int get hashCode => href.hashCode ^ progression.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressView &&
          runtimeType == other.runtimeType &&
          href == other.href &&
          progression == other.progression;
}

/// UTF-16 半开区间视图
class RangeView {
  final int start;
  final int end;

  const RangeView({
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RangeView &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

/// 搜索命中视图
class SearchHitView {
  final String bookId;
  final String bookTitle;
  final String href;
  final String chapterTitle;
  final String snippet;
  final List<RangeView> ranges;
  final double? score;

  const SearchHitView({
    required this.bookId,
    required this.bookTitle,
    required this.href,
    required this.chapterTitle,
    required this.snippet,
    required this.ranges,
    this.score,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      bookTitle.hashCode ^
      href.hashCode ^
      chapterTitle.hashCode ^
      snippet.hashCode ^
      ranges.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHitView &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          bookTitle == other.bookTitle &&
          href == other.href &&
          chapterTitle == other.chapterTitle &&
          snippet == other.snippet &&
          ranges == other.ranges &&
          score == other.score;
}

/// 搜索范围视图（`all_books=true` 时忽略 `book_id`）
class SearchScopeView {
  final bool allBooks;
  final String? bookId;
  final List<String> formats;

  const SearchScopeView({
    required this.allBooks,
    this.bookId,
    required this.formats,
  });

  @override
  int get hashCode => allBooks.hashCode ^ bookId.hashCode ^ formats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchScopeView &&
          runtimeType == other.runtimeType &&
          allBooks == other.allBooks &&
          bookId == other.bookId &&
          formats == other.formats;
}

/// 朗读句子块视图（字段与 Dart `SentenceChunk` 一一对应）
class SentenceChunkView {
  /// 章内句序号（0 起，供 `TtsSentenceDone(index)` 回传）
  final int index;
  final String text;

  /// UTF-16 code unit，半开区间 `[start, end)`
  final int charStart;
  final int charEnd;
  final LocatorView locator;

  const SentenceChunkView({
    required this.index,
    required this.text,
    required this.charStart,
    required this.charEnd,
    required this.locator,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      text.hashCode ^
      charStart.hashCode ^
      charEnd.hashCode ^
      locator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentenceChunkView &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          text == other.text &&
          charStart == other.charStart &&
          charEnd == other.charEnd &&
          locator == other.locator;
}

/// 翻译配置视图（REQ-006 决策点2，US-15；**绝不返回明文 key**）
class TranslateConfigView {
  /// "auto" | "offline" | "deepl" | "echo"（= default_provider）
  final String provider;

  /// `DeepLProvider::key_is_missing` 语义（空串=false）
  final bool hasDeeplKey;

  /// 固定掩码 `••••••••`；无 key 为 None；绝不返回明文。
  final String? deeplKeyMasked;

  const TranslateConfigView({
    required this.provider,
    required this.hasDeeplKey,
    this.deeplKeyMasked,
  });

  @override
  int get hashCode =>
      provider.hashCode ^ hasDeeplKey.hashCode ^ deeplKeyMasked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateConfigView &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          hasDeeplKey == other.hasDeeplKey &&
          deeplKeyMasked == other.deeplKeyMasked;
}

/// 译文视图（from_cache 标注缓存命中，US-10/13；fallback_reason REQ-006 US-17/18）
class TranslationView {
  final String text;
  final String from;
  final String to;
  final String provider;
  final bool fromCache;

  /// 回退原因（如"在线失败，已回退离线"）；未回退为 None。
  final String? fallbackReason;

  const TranslationView({
    required this.text,
    required this.from,
    required this.to,
    required this.provider,
    required this.fromCache,
    this.fallbackReason,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      from.hashCode ^
      to.hashCode ^
      provider.hashCode ^
      fromCache.hashCode ^
      fallbackReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          from == other.from &&
          to == other.to &&
          provider == other.provider &&
          fromCache == other.fromCache &&
          fallbackReason == other.fallbackReason;
}
