// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected String dco_decode_String(dynamic raw);

@protected BookSummary dco_decode_book_summary(dynamic raw);

@protected BookView dco_decode_book_view(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected DictEntryView dco_decode_box_autoadd_dict_entry_view(dynamic raw);

@protected ProgressView dco_decode_box_autoadd_progress_view(dynamic raw);

@protected ChapterView dco_decode_chapter_view(dynamic raw);

@protected DictEntryView dco_decode_dict_entry_view(dynamic raw);

@protected DictInfoView dco_decode_dict_info_view(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<BookSummary> dco_decode_list_book_summary(dynamic raw);

@protected List<ChapterView> dco_decode_list_chapter_view(dynamic raw);

@protected List<DictInfoView> dco_decode_list_dict_info_view(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected DictEntryView? dco_decode_opt_box_autoadd_dict_entry_view(dynamic raw);

@protected ProgressView? dco_decode_opt_box_autoadd_progress_view(dynamic raw);

@protected ProgressView dco_decode_progress_view(dynamic raw);

@protected TranslationView dco_decode_translation_view(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected BookSummary sse_decode_book_summary(SseDeserializer deserializer);

@protected BookView sse_decode_book_view(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected DictEntryView sse_decode_box_autoadd_dict_entry_view(SseDeserializer deserializer);

@protected ProgressView sse_decode_box_autoadd_progress_view(SseDeserializer deserializer);

@protected ChapterView sse_decode_chapter_view(SseDeserializer deserializer);

@protected DictEntryView sse_decode_dict_entry_view(SseDeserializer deserializer);

@protected DictInfoView sse_decode_dict_info_view(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<BookSummary> sse_decode_list_book_summary(SseDeserializer deserializer);

@protected List<ChapterView> sse_decode_list_chapter_view(SseDeserializer deserializer);

@protected List<DictInfoView> sse_decode_list_dict_info_view(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected DictEntryView? sse_decode_opt_box_autoadd_dict_entry_view(SseDeserializer deserializer);

@protected ProgressView? sse_decode_opt_box_autoadd_progress_view(SseDeserializer deserializer);

@protected ProgressView sse_decode_progress_view(SseDeserializer deserializer);

@protected TranslationView sse_decode_translation_view(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_book_summary(BookSummary self, SseSerializer serializer);

@protected void sse_encode_book_view(BookView self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_dict_entry_view(DictEntryView self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_progress_view(ProgressView self, SseSerializer serializer);

@protected void sse_encode_chapter_view(ChapterView self, SseSerializer serializer);

@protected void sse_encode_dict_entry_view(DictEntryView self, SseSerializer serializer);

@protected void sse_encode_dict_info_view(DictInfoView self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_book_summary(List<BookSummary> self, SseSerializer serializer);

@protected void sse_encode_list_chapter_view(List<ChapterView> self, SseSerializer serializer);

@protected void sse_encode_list_dict_info_view(List<DictInfoView> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_dict_entry_view(DictEntryView? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_progress_view(ProgressView? self, SseSerializer serializer);

@protected void sse_encode_progress_view(ProgressView self, SseSerializer serializer);

@protected void sse_encode_translation_view(TranslationView self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            
        }
        