// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 245810283;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'reader_core',
    ioDirectory: '../core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBookChapterHtml(
      {required String id, required String href});

  Future<BookView> crateApiBookOpen({required String id});

  Future<Uint8List> crateApiBookResource(
      {required String id, required String path});

  Future<DictInfoView> crateApiDictInstall({required String path});

  Future<List<DictInfoView>> crateApiDictList();

  Future<DictEntryView?> crateApiDictLookup(
      {required String word, String? dictId});

  Future<void> crateApiDictRemove({required String dictId});

  Future<BookSummary> crateApiLibraryImport({required String path});

  Future<List<BookSummary>> crateApiLibraryList();

  Future<void> crateApiLibraryOpen({required String dataDir});

  Future<void> crateApiLibraryRemove({required String id});

  Future<AnnotationView> crateApiNotesCreate(
      {required String bookId,
      required String href,
      required String text,
      required double progression,
      required String kind,
      String? color,
      String? noteText});

  Future<void> crateApiNotesDelete({required String noteId});

  Future<int> crateApiNotesDeleteAll({required String bookId});

  Future<int> crateApiNotesDeleteMany({required List<String> noteIds});

  Future<ExportSummaryView> crateApiNotesExport(
      {required String bookId, required String fmt, required String outPath});

  Future<List<NoteGroupView>> crateApiNotesList({required String bookId});

  Future<LocatorView> crateApiNotesResolve({required String noteId});

  Future<BookmarkToggleView> crateApiNotesToggleBookmark(
      {required String bookId,
      required String href,
      required double progression,
      String? snippet});

  Future<void> crateApiNotesUpdate(
      {required String noteId, required NotePatchView patch});

  Future<ProgressView?> crateApiProgressGet({required String id});

  Future<void> crateApiProgressSave(
      {required String id, required String href, required double progression});

  Future<List<SearchHitView>> crateApiSearch(
      {required String query, required SearchScopeView scope});

  Future<TranslationView> crateApiTranslate(
      {required String text, required String from, required String to});

  Future<void> crateApiTranslateCacheClear();

  Future<TranslateConfigView> crateApiTranslateGetConfig();

  Future<void> crateApiTranslateSetConfig(
      {required String provider, required String key});

  Future<void> crateApiTranslateSetStrategy({required String strategy});

  Future<ListenSettingsView> crateApiTtsListenSettingsGet();

  Future<void> crateApiTtsListenSettingsSet(
      {required ListenSettingsView settings});

  Future<LocatorView> crateApiTtsLocatorForSentence(
      {required String bookId, required String href, required int idx});

  Future<List<SentenceChunkView>> crateApiTtsSegment(
      {required String bookId, required String href});

  Future<int> crateApiTtsSentenceIndexAt(
      {required String bookId,
      required String href,
      required LocatorView locator});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBookChapterHtml(
      {required String id, required String href}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(href, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBookChapterHtmlConstMeta,
      argValues: [id, href],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBookChapterHtmlConstMeta => const TaskConstMeta(
        debugName: "book_chapter_html",
        argNames: ["id", "href"],
      );

  @override
  Future<BookView> crateApiBookOpen({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_book_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBookOpenConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBookOpenConstMeta => const TaskConstMeta(
        debugName: "book_open",
        argNames: ["id"],
      );

  @override
  Future<Uint8List> crateApiBookResource(
      {required String id, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBookResourceConstMeta,
      argValues: [id, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBookResourceConstMeta => const TaskConstMeta(
        debugName: "book_resource",
        argNames: ["id", "path"],
      );

  @override
  Future<DictInfoView> crateApiDictInstall({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dict_info_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDictInstallConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictInstallConstMeta => const TaskConstMeta(
        debugName: "dict_install",
        argNames: ["path"],
      );

  @override
  Future<List<DictInfoView>> crateApiDictList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dict_info_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDictListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictListConstMeta => const TaskConstMeta(
        debugName: "dict_list",
        argNames: [],
      );

  @override
  Future<DictEntryView?> crateApiDictLookup(
      {required String word, String? dictId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(word, serializer);
        sse_encode_opt_String(dictId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_dict_entry_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDictLookupConstMeta,
      argValues: [word, dictId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictLookupConstMeta => const TaskConstMeta(
        debugName: "dict_lookup",
        argNames: ["word", "dictId"],
      );

  @override
  Future<void> crateApiDictRemove({required String dictId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDictRemoveConstMeta,
      argValues: [dictId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictRemoveConstMeta => const TaskConstMeta(
        debugName: "dict_remove",
        argNames: ["dictId"],
      );

  @override
  Future<BookSummary> crateApiLibraryImport({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_book_summary,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLibraryImportConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryImportConstMeta => const TaskConstMeta(
        debugName: "library_import",
        argNames: ["path"],
      );

  @override
  Future<List<BookSummary>> crateApiLibraryList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_book_summary,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLibraryListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryListConstMeta => const TaskConstMeta(
        debugName: "library_list",
        argNames: [],
      );

  @override
  Future<void> crateApiLibraryOpen({required String dataDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLibraryOpenConstMeta,
      argValues: [dataDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryOpenConstMeta => const TaskConstMeta(
        debugName: "library_open",
        argNames: ["dataDir"],
      );

  @override
  Future<void> crateApiLibraryRemove({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLibraryRemoveConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryRemoveConstMeta => const TaskConstMeta(
        debugName: "library_remove",
        argNames: ["id"],
      );

  @override
  Future<AnnotationView> crateApiNotesCreate(
      {required String bookId,
      required String href,
      required String text,
      required double progression,
      required String kind,
      String? color,
      String? noteText}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(href, serializer);
        sse_encode_String(text, serializer);
        sse_encode_f_32(progression, serializer);
        sse_encode_String(kind, serializer);
        sse_encode_opt_String(color, serializer);
        sse_encode_opt_String(noteText, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_annotation_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesCreateConstMeta,
      argValues: [bookId, href, text, progression, kind, color, noteText],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesCreateConstMeta => const TaskConstMeta(
        debugName: "notes_create",
        argNames: [
          "bookId",
          "href",
          "text",
          "progression",
          "kind",
          "color",
          "noteText"
        ],
      );

  @override
  Future<void> crateApiNotesDelete({required String noteId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(noteId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesDeleteConstMeta,
      argValues: [noteId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesDeleteConstMeta => const TaskConstMeta(
        debugName: "notes_delete",
        argNames: ["noteId"],
      );

  @override
  Future<int> crateApiNotesDeleteAll({required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesDeleteAllConstMeta,
      argValues: [bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesDeleteAllConstMeta => const TaskConstMeta(
        debugName: "notes_delete_all",
        argNames: ["bookId"],
      );

  @override
  Future<int> crateApiNotesDeleteMany({required List<String> noteIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(noteIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesDeleteManyConstMeta,
      argValues: [noteIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesDeleteManyConstMeta => const TaskConstMeta(
        debugName: "notes_delete_many",
        argNames: ["noteIds"],
      );

  @override
  Future<ExportSummaryView> crateApiNotesExport(
      {required String bookId, required String fmt, required String outPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(fmt, serializer);
        sse_encode_String(outPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_export_summary_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesExportConstMeta,
      argValues: [bookId, fmt, outPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesExportConstMeta => const TaskConstMeta(
        debugName: "notes_export",
        argNames: ["bookId", "fmt", "outPath"],
      );

  @override
  Future<List<NoteGroupView>> crateApiNotesList({required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_note_group_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesListConstMeta,
      argValues: [bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesListConstMeta => const TaskConstMeta(
        debugName: "notes_list",
        argNames: ["bookId"],
      );

  @override
  Future<LocatorView> crateApiNotesResolve({required String noteId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(noteId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_locator_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesResolveConstMeta,
      argValues: [noteId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesResolveConstMeta => const TaskConstMeta(
        debugName: "notes_resolve",
        argNames: ["noteId"],
      );

  @override
  Future<BookmarkToggleView> crateApiNotesToggleBookmark(
      {required String bookId,
      required String href,
      required double progression,
      String? snippet}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(href, serializer);
        sse_encode_f_32(progression, serializer);
        sse_encode_opt_String(snippet, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bookmark_toggle_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesToggleBookmarkConstMeta,
      argValues: [bookId, href, progression, snippet],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesToggleBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "notes_toggle_bookmark",
        argNames: ["bookId", "href", "progression", "snippet"],
      );

  @override
  Future<void> crateApiNotesUpdate(
      {required String noteId, required NotePatchView patch}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(noteId, serializer);
        sse_encode_box_autoadd_note_patch_view(patch, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNotesUpdateConstMeta,
      argValues: [noteId, patch],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNotesUpdateConstMeta => const TaskConstMeta(
        debugName: "notes_update",
        argNames: ["noteId", "patch"],
      );

  @override
  Future<ProgressView?> crateApiProgressGet({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_progress_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProgressGetConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProgressGetConstMeta => const TaskConstMeta(
        debugName: "progress_get",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiProgressSave(
      {required String id, required String href, required double progression}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(href, serializer);
        sse_encode_f_32(progression, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProgressSaveConstMeta,
      argValues: [id, href, progression],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProgressSaveConstMeta => const TaskConstMeta(
        debugName: "progress_save",
        argNames: ["id", "href", "progression"],
      );

  @override
  Future<List<SearchHitView>> crateApiSearch(
      {required String query, required SearchScopeView scope}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_box_autoadd_search_scope_view(scope, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_search_hit_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchConstMeta,
      argValues: [query, scope],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchConstMeta => const TaskConstMeta(
        debugName: "search",
        argNames: ["query", "scope"],
      );

  @override
  Future<TranslationView> crateApiTranslate(
      {required String text, required String from, required String to}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(to, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_translation_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranslateConstMeta,
      argValues: [text, from, to],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateConstMeta => const TaskConstMeta(
        debugName: "translate",
        argNames: ["text", "from", "to"],
      );

  @override
  Future<void> crateApiTranslateCacheClear() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranslateCacheClearConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateCacheClearConstMeta =>
      const TaskConstMeta(
        debugName: "translate_cache_clear",
        argNames: [],
      );

  @override
  Future<TranslateConfigView> crateApiTranslateGetConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_translate_config_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranslateGetConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateGetConfigConstMeta => const TaskConstMeta(
        debugName: "translate_get_config",
        argNames: [],
      );

  @override
  Future<void> crateApiTranslateSetConfig(
      {required String provider, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(provider, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranslateSetConfigConstMeta,
      argValues: [provider, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateSetConfigConstMeta => const TaskConstMeta(
        debugName: "translate_set_config",
        argNames: ["provider", "key"],
      );

  @override
  Future<void> crateApiTranslateSetStrategy({required String strategy}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(strategy, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTranslateSetStrategyConstMeta,
      argValues: [strategy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTranslateSetStrategyConstMeta =>
      const TaskConstMeta(
        debugName: "translate_set_strategy",
        argNames: ["strategy"],
      );

  @override
  Future<ListenSettingsView> crateApiTtsListenSettingsGet() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_listen_settings_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTtsListenSettingsGetConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTtsListenSettingsGetConstMeta =>
      const TaskConstMeta(
        debugName: "tts_listen_settings_get",
        argNames: [],
      );

  @override
  Future<void> crateApiTtsListenSettingsSet(
      {required ListenSettingsView settings}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_listen_settings_view(settings, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTtsListenSettingsSetConstMeta,
      argValues: [settings],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTtsListenSettingsSetConstMeta =>
      const TaskConstMeta(
        debugName: "tts_listen_settings_set",
        argNames: ["settings"],
      );

  @override
  Future<LocatorView> crateApiTtsLocatorForSentence(
      {required String bookId, required String href, required int idx}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(href, serializer);
        sse_encode_u_32(idx, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_locator_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTtsLocatorForSentenceConstMeta,
      argValues: [bookId, href, idx],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTtsLocatorForSentenceConstMeta =>
      const TaskConstMeta(
        debugName: "tts_locator_for_sentence",
        argNames: ["bookId", "href", "idx"],
      );

  @override
  Future<List<SentenceChunkView>> crateApiTtsSegment(
      {required String bookId, required String href}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(href, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_sentence_chunk_view,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTtsSegmentConstMeta,
      argValues: [bookId, href],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTtsSegmentConstMeta => const TaskConstMeta(
        debugName: "tts_segment",
        argNames: ["bookId", "href"],
      );

  @override
  Future<int> crateApiTtsSentenceIndexAt(
      {required String bookId,
      required String href,
      required LocatorView locator}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookId, serializer);
        sse_encode_String(href, serializer);
        sse_encode_box_autoadd_locator_view(locator, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTtsSentenceIndexAtConstMeta,
      argValues: [bookId, href, locator],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTtsSentenceIndexAtConstMeta => const TaskConstMeta(
        debugName: "tts_sentence_index_at",
        argNames: ["bookId", "href", "locator"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnnotationView dco_decode_annotation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return AnnotationView(
      id: dco_decode_String(arr[0]),
      bookId: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      color: dco_decode_opt_String(arr[3]),
      href: dco_decode_String(arr[4]),
      progression: dco_decode_f_32(arr[5]),
      snippet: dco_decode_opt_String(arr[6]),
      noteText: dco_decode_opt_String(arr[7]),
      start: dco_decode_opt_box_autoadd_u_32(arr[8]),
      end: dco_decode_opt_box_autoadd_u_32(arr[9]),
      createdAt: dco_decode_i_64(arr[10]),
      updatedAt: dco_decode_i_64(arr[11]),
      syncStatus: dco_decode_String(arr[12]),
    );
  }

  @protected
  BookSummary dco_decode_book_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BookSummary(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      authors: dco_decode_list_String(arr[2]),
      language: dco_decode_opt_String(arr[3]),
      format: dco_decode_String(arr[4]),
    );
  }

  @protected
  BookView dco_decode_book_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookView(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      chapters: dco_decode_list_chapter_view(arr[2]),
    );
  }

  @protected
  BookmarkToggleView dco_decode_bookmark_toggle_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BookmarkToggleView(
      bookmarked: dco_decode_bool(arr[0]),
      noteId: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DictEntryView dco_decode_box_autoadd_dict_entry_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dict_entry_view(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ListenSettingsView dco_decode_box_autoadd_listen_settings_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_listen_settings_view(raw);
  }

  @protected
  LocatorView dco_decode_box_autoadd_locator_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_locator_view(raw);
  }

  @protected
  NotePatchView dco_decode_box_autoadd_note_patch_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note_patch_view(raw);
  }

  @protected
  ProgressView dco_decode_box_autoadd_progress_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_progress_view(raw);
  }

  @protected
  SearchScopeView dco_decode_box_autoadd_search_scope_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_scope_view(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChapterView dco_decode_chapter_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChapterView(
      title: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      href: dco_decode_String(arr[2]),
    );
  }

  @protected
  DictEntryView dco_decode_dict_entry_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DictEntryView(
      word: dco_decode_String(arr[0]),
      phonetic: dco_decode_opt_String(arr[1]),
      pos: dco_decode_opt_String(arr[2]),
      definition: dco_decode_String(arr[3]),
      example: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DictInfoView dco_decode_dict_info_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DictInfoView(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      wordCount: dco_decode_u_64(arr[2]),
      path: dco_decode_String(arr[3]),
    );
  }

  @protected
  ExportSummaryView dco_decode_export_summary_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportSummaryView(
      path: dco_decode_String(arr[0]),
      noteCount: dco_decode_u_32(arr[1]),
      format: dco_decode_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AnnotationView> dco_decode_list_annotation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_annotation_view).toList();
  }

  @protected
  List<BookSummary> dco_decode_list_book_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_summary).toList();
  }

  @protected
  List<ChapterView> dco_decode_list_chapter_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_view).toList();
  }

  @protected
  List<DictInfoView> dco_decode_list_dict_info_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dict_info_view).toList();
  }

  @protected
  List<NoteGroupView> dco_decode_list_note_group_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_group_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RangeView> dco_decode_list_range_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_range_view).toList();
  }

  @protected
  List<SearchHitView> dco_decode_list_search_hit_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit_view).toList();
  }

  @protected
  List<SentenceChunkView> dco_decode_list_sentence_chunk_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sentence_chunk_view).toList();
  }

  @protected
  ListenSettingsView dco_decode_listen_settings_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ListenSettingsView(
      voiceId: dco_decode_String(arr[0]),
      speed: dco_decode_f_32(arr[1]),
      autoNext: dco_decode_bool(arr[2]),
    );
  }

  @protected
  LocatorView dco_decode_locator_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LocatorView(
      bookId: dco_decode_String(arr[0]),
      href: dco_decode_String(arr[1]),
      progression: dco_decode_f_32(arr[2]),
      totalProgression: dco_decode_f_32(arr[3]),
      snippet: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  NoteGroupView dco_decode_note_group_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NoteGroupView(
      chapterTitle: dco_decode_String(arr[0]),
      href: dco_decode_String(arr[1]),
      notes: dco_decode_list_annotation_view(arr[2]),
    );
  }

  @protected
  NotePatchView dco_decode_note_patch_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NotePatchView(
      noteText: dco_decode_opt_String(arr[0]),
      color: dco_decode_opt_String(arr[1]),
      kind: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DictEntryView? dco_decode_opt_box_autoadd_dict_entry_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dict_entry_view(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  ProgressView? dco_decode_opt_box_autoadd_progress_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_progress_view(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ProgressView dco_decode_progress_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProgressView(
      href: dco_decode_String(arr[0]),
      progression: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  RangeView dco_decode_range_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RangeView(
      start: dco_decode_u_32(arr[0]),
      end: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  SearchHitView dco_decode_search_hit_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SearchHitView(
      bookId: dco_decode_String(arr[0]),
      bookTitle: dco_decode_String(arr[1]),
      href: dco_decode_String(arr[2]),
      chapterTitle: dco_decode_String(arr[3]),
      chapterIndex: dco_decode_u_32(arr[4]),
      snippet: dco_decode_String(arr[5]),
      ranges: dco_decode_list_range_view(arr[6]),
      score: dco_decode_opt_box_autoadd_f_64(arr[7]),
    );
  }

  @protected
  SearchScopeView dco_decode_search_scope_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SearchScopeView(
      allBooks: dco_decode_bool(arr[0]),
      bookId: dco_decode_opt_String(arr[1]),
      formats: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  SentenceChunkView dco_decode_sentence_chunk_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SentenceChunkView(
      index: dco_decode_u_32(arr[0]),
      text: dco_decode_String(arr[1]),
      charStart: dco_decode_u_32(arr[2]),
      charEnd: dco_decode_u_32(arr[3]),
      locator: dco_decode_locator_view(arr[4]),
    );
  }

  @protected
  TranslateConfigView dco_decode_translate_config_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TranslateConfigView(
      provider: dco_decode_String(arr[0]),
      hasDeeplKey: dco_decode_bool(arr[1]),
      deeplKeyMasked: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  TranslationView dco_decode_translation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TranslationView(
      text: dco_decode_String(arr[0]),
      from: dco_decode_String(arr[1]),
      to: dco_decode_String(arr[2]),
      provider: dco_decode_String(arr[3]),
      fromCache: dco_decode_bool(arr[4]),
      fallbackReason: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnnotationView sse_decode_annotation_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_bookId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_color = sse_decode_opt_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_progression = sse_decode_f_32(deserializer);
    var var_snippet = sse_decode_opt_String(deserializer);
    var var_noteText = sse_decode_opt_String(deserializer);
    var var_start = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_end = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_syncStatus = sse_decode_String(deserializer);
    return AnnotationView(
        id: var_id,
        bookId: var_bookId,
        kind: var_kind,
        color: var_color,
        href: var_href,
        progression: var_progression,
        snippet: var_snippet,
        noteText: var_noteText,
        start: var_start,
        end: var_end,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        syncStatus: var_syncStatus);
  }

  @protected
  BookSummary sse_decode_book_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_authors = sse_decode_list_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    return BookSummary(
        id: var_id,
        title: var_title,
        authors: var_authors,
        language: var_language,
        format: var_format);
  }

  @protected
  BookView sse_decode_book_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_chapters = sse_decode_list_chapter_view(deserializer);
    return BookView(id: var_id, title: var_title, chapters: var_chapters);
  }

  @protected
  BookmarkToggleView sse_decode_bookmark_toggle_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookmarked = sse_decode_bool(deserializer);
    var var_noteId = sse_decode_opt_String(deserializer);
    return BookmarkToggleView(bookmarked: var_bookmarked, noteId: var_noteId);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DictEntryView sse_decode_box_autoadd_dict_entry_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dict_entry_view(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  ListenSettingsView sse_decode_box_autoadd_listen_settings_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_listen_settings_view(deserializer));
  }

  @protected
  LocatorView sse_decode_box_autoadd_locator_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_locator_view(deserializer));
  }

  @protected
  NotePatchView sse_decode_box_autoadd_note_patch_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note_patch_view(deserializer));
  }

  @protected
  ProgressView sse_decode_box_autoadd_progress_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_progress_view(deserializer));
  }

  @protected
  SearchScopeView sse_decode_box_autoadd_search_scope_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_scope_view(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ChapterView sse_decode_chapter_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    return ChapterView(title: var_title, text: var_text, href: var_href);
  }

  @protected
  DictEntryView sse_decode_dict_entry_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_word = sse_decode_String(deserializer);
    var var_phonetic = sse_decode_opt_String(deserializer);
    var var_pos = sse_decode_opt_String(deserializer);
    var var_definition = sse_decode_String(deserializer);
    var var_example = sse_decode_opt_String(deserializer);
    return DictEntryView(
        word: var_word,
        phonetic: var_phonetic,
        pos: var_pos,
        definition: var_definition,
        example: var_example);
  }

  @protected
  DictInfoView sse_decode_dict_info_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_wordCount = sse_decode_u_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    return DictInfoView(
        id: var_id, name: var_name, wordCount: var_wordCount, path: var_path);
  }

  @protected
  ExportSummaryView sse_decode_export_summary_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_noteCount = sse_decode_u_32(deserializer);
    var var_format = sse_decode_String(deserializer);
    return ExportSummaryView(
        path: var_path, noteCount: var_noteCount, format: var_format);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnnotationView> sse_decode_list_annotation_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnnotationView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_annotation_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookSummary> sse_decode_list_book_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterView> sse_decode_list_chapter_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<DictInfoView> sse_decode_list_dict_info_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DictInfoView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dict_info_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteGroupView> sse_decode_list_note_group_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteGroupView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_group_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RangeView> sse_decode_list_range_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RangeView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_range_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchHitView> sse_decode_list_search_hit_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHitView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<SentenceChunkView> sse_decode_list_sentence_chunk_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SentenceChunkView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sentence_chunk_view(deserializer));
    }
    return ans_;
  }

  @protected
  ListenSettingsView sse_decode_listen_settings_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_voiceId = sse_decode_String(deserializer);
    var var_speed = sse_decode_f_32(deserializer);
    var var_autoNext = sse_decode_bool(deserializer);
    return ListenSettingsView(
        voiceId: var_voiceId, speed: var_speed, autoNext: var_autoNext);
  }

  @protected
  LocatorView sse_decode_locator_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookId = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_progression = sse_decode_f_32(deserializer);
    var var_totalProgression = sse_decode_f_32(deserializer);
    var var_snippet = sse_decode_opt_String(deserializer);
    return LocatorView(
        bookId: var_bookId,
        href: var_href,
        progression: var_progression,
        totalProgression: var_totalProgression,
        snippet: var_snippet);
  }

  @protected
  NoteGroupView sse_decode_note_group_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterTitle = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_notes = sse_decode_list_annotation_view(deserializer);
    return NoteGroupView(
        chapterTitle: var_chapterTitle, href: var_href, notes: var_notes);
  }

  @protected
  NotePatchView sse_decode_note_patch_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_noteText = sse_decode_opt_String(deserializer);
    var var_color = sse_decode_opt_String(deserializer);
    var var_kind = sse_decode_opt_String(deserializer);
    return NotePatchView(
        noteText: var_noteText, color: var_color, kind: var_kind);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DictEntryView? sse_decode_opt_box_autoadd_dict_entry_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dict_entry_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressView? sse_decode_opt_box_autoadd_progress_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_progress_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressView sse_decode_progress_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_href = sse_decode_String(deserializer);
    var var_progression = sse_decode_f_32(deserializer);
    return ProgressView(href: var_href, progression: var_progression);
  }

  @protected
  RangeView sse_decode_range_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    return RangeView(start: var_start, end: var_end);
  }

  @protected
  SearchHitView sse_decode_search_hit_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookId = sse_decode_String(deserializer);
    var var_bookTitle = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_chapterTitle = sse_decode_String(deserializer);
    var var_chapterIndex = sse_decode_u_32(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_ranges = sse_decode_list_range_view(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    return SearchHitView(
        bookId: var_bookId,
        bookTitle: var_bookTitle,
        href: var_href,
        chapterTitle: var_chapterTitle,
        chapterIndex: var_chapterIndex,
        snippet: var_snippet,
        ranges: var_ranges,
        score: var_score);
  }

  @protected
  SearchScopeView sse_decode_search_scope_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_allBooks = sse_decode_bool(deserializer);
    var var_bookId = sse_decode_opt_String(deserializer);
    var var_formats = sse_decode_list_String(deserializer);
    return SearchScopeView(
        allBooks: var_allBooks, bookId: var_bookId, formats: var_formats);
  }

  @protected
  SentenceChunkView sse_decode_sentence_chunk_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_charStart = sse_decode_u_32(deserializer);
    var var_charEnd = sse_decode_u_32(deserializer);
    var var_locator = sse_decode_locator_view(deserializer);
    return SentenceChunkView(
        index: var_index,
        text: var_text,
        charStart: var_charStart,
        charEnd: var_charEnd,
        locator: var_locator);
  }

  @protected
  TranslateConfigView sse_decode_translate_config_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_hasDeeplKey = sse_decode_bool(deserializer);
    var var_deeplKeyMasked = sse_decode_opt_String(deserializer);
    return TranslateConfigView(
        provider: var_provider,
        hasDeeplKey: var_hasDeeplKey,
        deeplKeyMasked: var_deeplKeyMasked);
  }

  @protected
  TranslationView sse_decode_translation_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_fromCache = sse_decode_bool(deserializer);
    var var_fallbackReason = sse_decode_opt_String(deserializer);
    return TranslationView(
        text: var_text,
        from: var_from,
        to: var_to,
        provider: var_provider,
        fromCache: var_fromCache,
        fallbackReason: var_fallbackReason);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_annotation_view(
      AnnotationView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.bookId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.color, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_f_32(self.progression, serializer);
    sse_encode_opt_String(self.snippet, serializer);
    sse_encode_opt_String(self.noteText, serializer);
    sse_encode_opt_box_autoadd_u_32(self.start, serializer);
    sse_encode_opt_box_autoadd_u_32(self.end, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_String(self.syncStatus, serializer);
  }

  @protected
  void sse_encode_book_summary(BookSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_String(self.format, serializer);
  }

  @protected
  void sse_encode_book_view(BookView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_chapter_view(self.chapters, serializer);
  }

  @protected
  void sse_encode_bookmark_toggle_view(
      BookmarkToggleView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.bookmarked, serializer);
    sse_encode_opt_String(self.noteId, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dict_entry_view(
      DictEntryView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dict_entry_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_listen_settings_view(
      ListenSettingsView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_listen_settings_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_locator_view(
      LocatorView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_locator_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_note_patch_view(
      NotePatchView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_patch_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_progress_view(
      ProgressView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_progress_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_scope_view(
      SearchScopeView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_scope_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_chapter_view(ChapterView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.href, serializer);
  }

  @protected
  void sse_encode_dict_entry_view(
      DictEntryView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.word, serializer);
    sse_encode_opt_String(self.phonetic, serializer);
    sse_encode_opt_String(self.pos, serializer);
    sse_encode_String(self.definition, serializer);
    sse_encode_opt_String(self.example, serializer);
  }

  @protected
  void sse_encode_dict_info_view(DictInfoView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.wordCount, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_export_summary_view(
      ExportSummaryView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.noteCount, serializer);
    sse_encode_String(self.format, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_annotation_view(
      List<AnnotationView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_annotation_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_summary(
      List<BookSummary> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_view(
      List<ChapterView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dict_info_view(
      List<DictInfoView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dict_info_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_group_view(
      List<NoteGroupView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_group_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_range_view(
      List<RangeView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_range_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_hit_view(
      List<SearchHitView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sentence_chunk_view(
      List<SentenceChunkView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sentence_chunk_view(item, serializer);
    }
  }

  @protected
  void sse_encode_listen_settings_view(
      ListenSettingsView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.voiceId, serializer);
    sse_encode_f_32(self.speed, serializer);
    sse_encode_bool(self.autoNext, serializer);
  }

  @protected
  void sse_encode_locator_view(LocatorView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bookId, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_f_32(self.progression, serializer);
    sse_encode_f_32(self.totalProgression, serializer);
    sse_encode_opt_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_note_group_view(
      NoteGroupView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chapterTitle, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_list_annotation_view(self.notes, serializer);
  }

  @protected
  void sse_encode_note_patch_view(
      NotePatchView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.noteText, serializer);
    sse_encode_opt_String(self.color, serializer);
    sse_encode_opt_String(self.kind, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dict_entry_view(
      DictEntryView? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dict_entry_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_progress_view(
      ProgressView? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_progress_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_view(ProgressView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.href, serializer);
    sse_encode_f_32(self.progression, serializer);
  }

  @protected
  void sse_encode_range_view(RangeView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
  }

  @protected
  void sse_encode_search_hit_view(
      SearchHitView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bookId, serializer);
    sse_encode_String(self.bookTitle, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_String(self.chapterTitle, serializer);
    sse_encode_u_32(self.chapterIndex, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_list_range_view(self.ranges, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
  }

  @protected
  void sse_encode_search_scope_view(
      SearchScopeView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.allBooks, serializer);
    sse_encode_opt_String(self.bookId, serializer);
    sse_encode_list_String(self.formats, serializer);
  }

  @protected
  void sse_encode_sentence_chunk_view(
      SentenceChunkView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_u_32(self.charStart, serializer);
    sse_encode_u_32(self.charEnd, serializer);
    sse_encode_locator_view(self.locator, serializer);
  }

  @protected
  void sse_encode_translate_config_view(
      TranslateConfigView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_bool(self.hasDeeplKey, serializer);
    sse_encode_opt_String(self.deeplKeyMasked, serializer);
  }

  @protected
  void sse_encode_translation_view(
      TranslationView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_bool(self.fromCache, serializer);
    sse_encode_opt_String(self.fallbackReason, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
